version: 0.2

phases:
  install:
    commands:
      - echo "Downloading AWS Lightsail Control Plugin..."
      - curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      - chmod +x /usr/local/bin/lightsailctl
      - echo "Lightsail plugin successfully installed."
      
  pre_build:
    commands:
      - echo "Showing env..."
      - env
      
  build:
    commands:
      - APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
      - echo "Building the Docker image for Python Cowsay version ${APP_VERSION}..."
      - docker build -t $IMAGE_NAME:$APP_VERSION .
      - docker images $IMAGE_NAME:$APP_VERSION
  
  post_build:
    commands:
      - APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
      - echo "Pushing image to Lightsail container service..."
      - aws lightsail push-container-image --region $AWS_REGION --service-name $LIGHTSAIL_SERVICE_NAME --label $IMAGE_NAME --image $IMAGE_NAME:$APP_VERSION || echo "FAILS"
      
