version: 0.2

phases:
  install:
    commands:
      - echo "Downloading AWS Lightsail Control Plugin..."
      - curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      - chmod +x /usr/local/bin/lightsailctl
      - echo "Lightsail plugin successfully installed."
      
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image for Python Cowsay...
