version: 0.2

phases:
  install:
    on-failure: ABORT
    commands:
      - echo "Downloading AWS Lightsail Control Plugin..."
      - curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"
      - chmod +x /usr/local/bin/lightsailctl
      - echo "Lightsail plugin successfully installed."
      
  pre_build:
    commands:
      - echo "Showing env..."
      - env
      
  build:
    on-failure: ABORT
    commands:
      - |
        echo "Parsing HEAD_REF: $CODEBUILD_WEBHOOK_HEAD_REF"
        APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
        # Default to main branch (development)
        [ -z "$APP_VERSION" ] && APP_VERSION="main"

        echo "Building the Docker image for Python Cowsay version ${APP_VERSION}..."
        docker build -t $IMAGE_NAME:$APP_VERSION .
        docker images $IMAGE_NAME:$APP_VERSION
  
  post_build:
    on-failure: ABORT
    commands:
      - |
        export APP_VERSION=$( echo $CODEBUILD_WEBHOOK_HEAD_REF | cut -d '/' -f 3 )
        # Default to main branch (development)
        [ -z "$APP_VERSION" ] && APP_VERSION="main"
        echo "Deploying version '${APP_VERSION}'..."
        
      - |
        echo "Pushing image to Lightsail container service '${APP_VERSION}'..."
        aws lightsail push-container-image --region $AWS_REGION --service-name $LIGHTSAIL_SERVICE_NAME --label $IMAGE_NAME --image $IMAGE_NAME:$APP_VERSION
        
        cat <<EOF > /tmp/lightsail-containers.json
        {
        "cowsay-api": {
          "image": ":${LIGHTSAIL_SERVICE_NAME}.${IMAGE_NAME}.latest",
            "environment": {
              "APP_WORKER": "4",
              "APP_BIND": "0.0.0.0:8080"
            },
            "ports": {
              "8080": "HTTP"
            }
          }
        }
        EOF
        
        cat <<EOF > /tmp/lightsail-endpoint.json
        {
          "containerName": "cowsay-api",
          "containerPort": 8080
        }
        EOF
        
        # Let's see if the files was created
        ls -l /tmp/*.json
        
      - |
        # Deploy container
        aws lightsail create-container-service-deployment \
          --service-name $LIGHTSAIL_SERVICE_NAME \
          --containers file:///tmp/lightsail-containers.json \
          --public-endpoint file:///tmp/lightsail-endpoint.json
